### ISSUE TITLE
gitCreatedAt doesnt work after deploying on gh-pages

### ISSUE THREAD

**Issue by thepenielcho** [dword-design/nuxt-content-git#39]
gitCreatedAt doesnt work after deploying on github actions to gh-pages 😭 
they all just end up being today's date. am i the only one struggling w/ this?
if not, please let me know how to fix the issues 😞 
(and ofc i did install nuxt-content-git via npm)

this is my _slug file,
```html
...
            <p class="text-base md:text-xl text-gray-500 text-center mb-16">
                {{formatDate(article.gitCreatedAt)}} · by
                <span v-for="memberAuthor of member" :key="memberAuthor"> 
                    <nuxt-link :to="{path: `/member/${memberAuthor.slug}`}" replace class="hover:underline">
                        {{memberAuthor.name}}
                    </nuxt-link>
                </span>
            </p>
...
```
this is my nuxt.config.js file,
```javascript
export default {
...
  modules: [

    //https://github.com/dword-design/nuxt-content-git
    ['nuxt-content-git', {
      createdAtName : 'gitCreatedAt',
      updatedAtName : 'gitUpdatedAt',
    }],

    // https://go.nuxtjs.dev/content
    '@nuxt/content',
    '@nuxtjs/google-analytics'

  ],
...
}
```
and this is my yml file for auto building and deploying on github actions.
```yml
name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
```

**Comment by dword-design** [comment]
@thepenielcho I think it could be that you do not fetch the whole history. I don't exactly know how the deployment to `gh-pages` works, but if I'm not mistaken, you generate the static files on GitHub actions and then they are uploaded to `gh-pages`. In this case you should be able to adjust `actions/checkout@master` like this:

```yaml
- name: Checkout
  uses: actions/checkout@master
  with:
    fetch-depth: 0
```

It will then clone the full repo instead of only a shallow clone.

Let me know if this works. I will adjust the doc accordingly.
